### ISSUE TITLE
Please add Go module

### ISSUE THREAD

**Issue by willfaught** [maraino/go-mock#16]
Hey @maraino! :)

**Comment by maraino** [comment]
Hi @willfaught, are you still using it, I only use gomock because of the code generation, and I've just realized, the original gomock is no longer maintained.

**Comment by willfaught** [comment]
By gomock, do you mean this repo? What do you mean by original gomock?

I use this repo sometimes to mock small things by hand.

**Comment by maraino** [comment]
I meant the `gomock` package from [github.com/golang/mock](https://github.com/golang/mock), but now maintained by [go.uber.org/mock](https://github.com/uber/mock)
